USE ISS_PRACTICE;

SELECT NAME FROM SYS.TABLES;

--CREATE TABLE EMPLOYEE(
--EMP_ID INT, 
--EMP_NAME VARCHAR(50), 
--SALARY INT, 
--GENDER CHAR CHECK(GENDER LIKE 'F' OR GENDER LIKE 'M' OR GENDER LIKE 'O'), 
--LOCATION VARCHAR(100)
--);

--INSERT INTO EMPLOYEE VALUES(1, 'EMILY JAMES', 60000, 'F', 'BOSTON');
--INSERT INTO EMPLOYEE VALUES(2, 'JAMES POTTER', 50000, 'M', 'LONDON');
--INSERT INTO EMPLOYEE VALUES(3, 'EMMA HEARD', 75000, 'F', 'MUMBAI');
--INSERT INTO EMPLOYEE VALUES(4, 'BRANDON LANE', 80000, 'M', 'SYDNEY');
--INSERT INTO EMPLOYEE VALUES(1, 'EMILY JAMES', 60000, 'F', 'BOSTON');
--INSERT INTO EMPLOYEE VALUES(2, 'JAMES POTTER', 50000, 'M', 'LONDON');
--INSERT INTO EMPLOYEE VALUES(5, 'LANE KIM', 90000, 'F', 'SEOUL');
--INSERT INTO EMPLOYEE VALUES(6, 'KAITO TAKASHI', 55000, 'F', 'TOKYO'); 
--INSERT INTO EMPLOYEE VALUES(7, 'JIMMY JIM', 40000, 'M', 'BOSTON');
--INSERT INTO EMPLOYEE VALUES(8, 'KELLY SWIFT' , 90000, 'F', 'BOSTON');

SELECT * FROM EMPLOYEE;

SELECT GENDER, COUNT(*) FROM EMPLOYEE WHERE GENDER='F' AND LOCATION='MUMBAI' GROUP BY GENDER;

SELECT LOCATION, MAX(SALARY) FROM EMPLOYEE GROUP BY LOCATION;

SELECT LOCATION, MAX(SALARY) AS SECOND_MAX_SALARY FROM EMPLOYEE E1 WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE E2 WHERE E1.LOCATION=E2.LOCATION)
GROUP BY LOCATION;

SELECT DISTINCT(EMP_ID), EMP_NAME, SALARY, LOCATION FROM EMPLOYEE;



